### ISSUE TITLE
Update labels/units dynamically 

### ISSUE THREAD

**Issue by MatthewReed303** [RainingComputers/picograph.js#3]
Is there any way to update the labels and units dynamically via javascript or all the graph parameters? 

For example my application has 3 states and each state has a different unit, I want to use the one graph to display the data of these states. eg state 1 is voltage mode and units and label display voltage, state 2 is current, state 3 is power

Is this possible or will I need 3 separate graphs? Thanks

**Comment by RainingComputers** [comment]
You can have multiple instances of the `Graph` class for each mode, but make them share the same canvas element, and when you want to switch mode, you can call `Graph.clear` on the previous mode and then call `Graph.update` on the next mode?

**Comment by MatthewReed303** [comment]
Hi @RainingComputers,

I have tried what you have suggested but the graph.clear is not clearing the labels and just adding them to the page one after the other. ( the text on the label does update ) After digging through the library I think this might have something todo with it: 

```
byID(labelDivID).innerHTML += `
        <div style="display: inline-block;">
            <svg width="10" height="10">
                <rect width="10" height="10" style="fill: ${color}"/>
            </svg> 
            ${labelSpan}
            ${valueSpan}
        <div>
    ` 
```

Every time this function is called it's just adding another element, I don't think the clear function removes this div?

**Comment by RainingComputers** [comment]
@MatthewReed303  I have added `switchGraph` function, you can see this demo: https://github.com/RainingComputers/picograph.js/blob/master/demo_switch.html

**Comment by MatthewReed303** [comment]
Hi @RainingComputers  thanks for the demo.

I gave the demo ago and I already have that all working. What I'm trying to achieve is something like this.

`myGraph.labels = ["myLabel1" , "myLabel2"]` this does not work

And then remove those labels and replace with new label ( don't want the old labels being displayed )

`myGraph.labels = ["newLabel1" , "newLabel2"]` this does not work

Note: this works fine for updating the units etc it's just the labels, the labels keep printing across the page. 

`myGraph.units = "V"` this works fine

`myGraph.units = "A"` this works fine

Do I need to create multiple instances of the graph class? graph1, graph2, graph3 etc Or can I just update existing graph instance parameters? 

I have a switch case statement and each state will be different values, labels, units ( I have 8 different states ) so just update the single graph instance would be ideal. Thanks!

**Comment by RainingComputers** [comment]
call `myGraph.createLegends()` after modifying the labels?

**Comment by MatthewReed303** [comment]
Hi @RainingComputers 

I have got it working by calling 8x different graph instances. Calling just one and trying to update it's label ( with `myGraph.createLegends()` ) was not working. I tracked the issue down the `this.noLabels` not returning the array length and it was only creating the one label. If I change it to this.labels.length It would create the label but no value or colour and would not update in the graph. 

I have got it working the way I want, just a bit clunky calling 8 different classes for the one graph to be displayed ( trying to reduce code size to fit on a microcontroller )

How hard would it be to add an array to the class to set the graph line colours manually if needed? Thanks

**Comment by RainingComputers** [comment]
> trying to reduce code size to fit on a microcontroller 

That's interesting!

I think it is possible to add a `updateConfig(labels, units)` and it would automatically update labels, units and colors properly. Calling the function would also clear the graph. 

Would this function solve your clunkyness?

**Comment by MatthewReed303** [comment]
Hi @RainingComputers 

Yes that would be great for updating graph dynamically. Maybe it would be worth adding the other useful configs available for future use? such as min/max, timestamp, scalesteps, autoscale, vert line, horizontal line. 

Is there an option to remove horizontal line but keep the values up the side?

What about choosing the line colour, just by entering colour hex into the config?

**Comment by RainingComputers** [comment]
> Is there an option to remove horizontal line but keep the values up the side?

I will add that option.

> such as min/max, timestamp, scalesteps, autoscale, vert line, horizontal line

I will try and make as much config as dynamic as possible, but might be little difficult.

Edit: on second thought, might not be

**Comment by RainingComputers** [comment]
This feature has been added now :)
